host := board

board-copy-scripts:
	scp ros.sh $(host):/home/xilinx
	scp activate_3d_camera.sh $(host):/home/xilinx
	scp roudi.sh $(host):/home/xilinx
	scp config.xml $(host):/home/xilinx
	scp introspection.sh $(host):/home/xilinx
	scp roudi-config.toml $(host):/home/xilinx
	scp set_camera_config.sh $(host):/home/xilinx
	scp start_nav2.sh $(host):/home/xilinx
	scp start_nav2_wifi.sh $(host):/home/xilinx
